### PR TITLE
Add basic docker installation and its documentation

### PR DESCRIPTION
**Pull request by matbgn**
Need to be completed with plugins but I have to work a bit by myself to add it before (not aware of all the possibilities of typemill yet).

### CODE REVIEW

**Comment by matbgn** [comment]
- [x] Plugins persistence done!

**Comment by trendschau** [comment]
Great! I will check it this weekend and merge, super cool that Typemill has a docker support now :)

**Comment by trendschau** [comment]
Not sure if it is a local problem but I got error messages when I tried with docker: 

```
debconf: delaying package configuration, since apt-utils is not installed
...
Step 4/15 : RUN docker-php-ext-install gd
 ---> Running in 2bd6a8b996bb
xz: (stdin): Compressed data is corrupt
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c docker-php-ext-install gd' returned a non-zero code: 2
```

**Comment by matbgn** [comment]
Hi I suspect a network problem.

I tried on a new fresh install at work (Windows machine) and successfully build it. Let me know if it persist ;-)

**Comment by trendschau** [comment]
Thank you, it worked now, but running without persistence leads to a long row of deprecation notices and fatal error, I did not try with the other mode yet. I will check all messages as soon as I get some more time...

**Comment by matbgn** [comment]
Nice catch!

As it was not my use case I failed to test it this way, sorry. I will give it a look this week again.

**Comment by trendschau** [comment]
BTW Typemill does not work with PHP 8.1 because the framework slim3 does not support it. I will start with Typemill V2 with a fully updated stack but that will take quite a lot of time. So it would be good to use PHP 8.0 in Docker (I still have to test 8.0 deeply this week). 

The current typemill stack is a bit outdated, but there are so many breaking changes, that it does not make sense to update Typemill V1. ...

**Comment by matbgn** [comment]
Ok I will fix the PHP version used by Docker.

What is your Masterplan (mainly when do you plan the switch) for the v2 in months / maybe years? Just to know as my company will continue to invest some time to the opensource project only if it makes sense in a realistic future.

**Comment by trendschau** [comment]
Masterplan is to switch in 2023 Q1/Q2. I just started so it is hard to say, but looking at other projects like statamic or kirby, 1 year of work seem realistic for a project like this. 

I will publish a branch for v2 as soon as there is some kind of skeleton.

**Comment by matbgn** [comment]
Thanks for your quick answer that seems totally fair. We are looking forward for the V2 dev branch also ;-)

For the dockerfile I sticked the PHP version to 8.0.x and it seems to fix all the issues in fact. See my screenshots below

image

Without any volumes mapped of course :

image

**Comment by trendschau** [comment]
Great, I tested it locally (with persistance only) and merged it with master. For some reason the request was still open so I merged it with github interface again. I will release 1.5.3.3 with small changes this week.

**Pull request merged**
