### PR TITLE
less is more

### PR DESCRIPTION
**Pull request by iusvar**
Less is better, thanks to the use of Vue filters (translate positioned in vue-meta.js):
- vue-i18n.min.js no longer needed (minus 23.8kb)
- vuejs-(lang).yaml files are not needed because their content has been transferred to (lang).yaml files (size more or less unchanged however there are fewer files to refer to)

### CODE REVIEW

**Comment by trendschau** [comment]
Hi iusvar, 

that is really great! It is part of the release 1.3.5 that has been pushed a second ago... 

I had some problems with merging, probably due to wrong rights of my local files, so I ended up migrating parts of it manually. I will close this request. We can also change the process, I can add you as a member to the typemill project and then you can create your branch directly here, what do you think? 

While testing I was thinking about two points: 

* If I don't have the translation folder installed, then I get sometimes the names with a questionmark at the end (?)
* Do you think it is possible to move the language-folder to the system folder (not sure about the read-rights)? It is easier for users to update typemill because he only has to delete and upload the system folder then. 

BTW I will separate the language settings for the author-ui-language and add another language setting for the tag in the frontend, because I for exampe use the english author-ui and write in german, so the frontend lang-tag should be "de". 

Let me know what you think about the proposals

**Comment by iusvar** [comment]
Hi trendschau,

I start from the points indicated:

- the question mark, for me, was only a kind of test to check if an english string has been translated into the selected language (it is found in vue-meta.js on line 8: in fact it is better to remove it)

- on the destination of the folder 'languages' I have no problem about it. Could 'system/author/languages/*.yaml' be fine?

- very agreed on the differentiation between front-end / back-end language

As for the process, if you think it can improve, add me as a member.

**Comment by trendschau** [comment]
Hi iusvar, 

great, I changed the vue-meta.js for next release in something like this, so that it looks fine in production:

`
Vue.filter('translate', function (value) {
  if (!value) return ''
  transvalue = value.replace(/[ ]/g,"_").replace(/[.]/g, "_").replace(/[-]/g, "_").replace(/[,]/g,"_").replace(/[(]/g,"_").replace(/[)]/g,"_").toUpperCase()
  translated_string = labels[transvalue]
  if(!translated_string || translated_string.length === 0){
    return value
  } else {
    return labels[transvalue]
  }
})
` 

* Yes, system/author/languages/*.yaml' is good, let us try :)
* Ok will do it. 

One question (and I got the same from a user today #124): We cannot translate text from plugins and themes this way because they will change depending on user. But we could load translations from the theme- and plugin-folders dynamically and then merge the translations. I do quite the same with the settings. I will try to do it in one of the next releases and I will probably prepare the form-builder for that already...

**Comment by iusvar** [comment]
Hi trendschau,
as you did with the default and user configurations, I am well on the way to separating the translations of the themes and plugins from the system translations ...

I also have a good solution for all the issues presented in an exemplary manner by @hide-me in [#124](https://github.com/typemill/typemill/issues/124)

**Pull request closed without merging**
