### PR TITLE
Improved Translations

### PR DESCRIPTION
**Pull request by hide-me**
### List of improvements:

- Added some missing strings with phrases (like missed options about _WEBSITE VISIBLE FOR_)

- All template strings was sorted **A --> Z**

- Russian translation was improved and completely finished

- All other lang files were extended (see the first string in this list)

- Added headers to all lang files, were:

1. First string English name of the language and then in brackets the native name of the language
2. Second string may consist of info about author/translator and contact info

- Finally, created python script which is making all lang files look the same (I mean structure of files for sure). _Idk should you add it to the next release zip-file or not, but in the process of developing/coding Typemill, this should be a very helpful tool!_

P.S. Waiting for a new release with cool features.

### CODE REVIEW

**Comment by trendschau** [comment]
great contribution, thank you! I will try to add to the next release 1.4.0 or (if that does not work because pretty complicated one) I will add to 1.4.1 which will be release shortly after 1.4.0

**Comment by hide-me** [comment]
Maybe release 1.4.0 will contain more strings for translation? May you add new strings now, because it will take time before "ready to use" translations.

And you are welcome 😅

**Comment by trendschau** [comment]
You can find version 1.4.0 in develop-branch. But I will probably publish it tomorrow because I am very very late with it. Version 1.4.1 will be published much faster, in 2 or 3 weeks I hope :)

**Comment by trendschau** [comment]
or wait, I am preparing release anyway, so I will push to master and then merge your changes

**Comment by trendschau** [comment]
ok, done, but it seems to have some conflicts now, do you think you can check those conflicts?

**Comment by trendschau** [comment]
A suggestion: Let us do that with version 1.4.1, is that fine for you? You can use the develop-branch, I will add my changes there frequently, and go live version 1.4.1 is planned in 2 or 3 weeks. Then I will publish 1.4.0 now. Ok?

**Comment by hide-me** [comment]
Sure! :)

**Comment by trendschau** [comment]
I close this one because it is already merged. Thank you !!

**Comment by hide-me** [comment]
You are welcome =D

**Pull request closed without merging**
