### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by iusvar**
Congratulations on your typemill.

I just made the internationalization. It is only an initial setting, it is not complete (js file management is still missing). 

The translation uses the language selected in Settings / System / Language-Attribute (HTML). 
For now the only languages provided are English and mine, Italian.

I hope it will interest you.

### CODE REVIEW

**Comment by svanlaere** [comment]
Hopefully this get merged, I like to provide Dutch i18n support.

**Comment by trendschau** [comment]
Wow, that looks great! I will check it for the next release, thank you for that great contribution!!

**Comment by trendschau** [comment]
Hi iusvar, I checked this locally now and I really like how it works! 

However, the symfony components are pretty large with 1 MB of code. This conflicts a bit with the goal of Typemill to be lightweight and floppy sized (core less than 1.44 MB gzipped). I just moved the plugins to the new plugin collection page in order to reduce the size of Typemill core again.

My thoughts (please correct me if I am wrong): We already have a YAML parser in Typemill. We only need a simple logic to load the yaml-translation files (we could move them to the settings-folder) and another twig-extension to add the trans-filter (or a twig-function). I would prefer to code a simple solution by hand and avoid the components. What do you think?

**Comment by iusvar** [comment]
Hi, I like that you want to keep the typemill core as light as possible.

My proposal was a quick solution because I had read about some who had asked you for this functionality and since I had already prepared it for me, I thought of proposing it as it is.

I also agree on your exposed thoughts: a customized function or filter would be an ideal solution. 

With your roadmap in mind, I will try to propose a suitable solution (I don't know with what timing), unless you want to take care of it yourself.

 I appreciate your frankness.

**Comment by trendschau** [comment]
Great to hear, I think many users will highly appreciate a translation feature and it would be great if you find a lightweight solution. A new Typemill version is published every 2 or 3 weeks so I can add it to a release whenever it is ready.

**Comment by iusvar** [comment]
I take the liberty of closing it because it is out of date

**Pull request closed without merging**
